### ISSUE TITLE
Tooltip improvements

### ISSUE THREAD

**Issue by igorschoester** [Yoast/ui-library-storybook#15]
Regarding the fancy new Tooltip: https://github.com/Yoast/wordpress-seo/pull/21111
I see some room for improvements 😅

When adding way too much text, it keeps to one line. Even when going out of the Storybook bounds, it creates a horizontal scrollbar (that you can't scroll due to the hovering).

And if you're there, some minor things:
* I think adding props that are not needed is not great on a library level. You can't enforce the `aria-describedby` from the Tooltip element level. But you can add the `id` through the prop spread already, even if not specified as a prop at all.
* Why is the story Badge rendered as a `button`?
* If you show the code in the story, the Badge shows up as `[object Object]` due to the forwardRef trouble. Until we remove WP element, I think we should use the `StorybookComponent` so it displays nicely in the code.

**Comment by d-claassen** [comment]
2 more improvements:

1. Add the `isVisible` property to the proptypes.
2. Make sure the `Factory` story is as basic as possible and connects to the options in the ArgsTable to showcase what the tooltip can do. Having the "badge-shows-a-tooltip-on-hover" story is great, but should be a separate story.

**Comment by Jordi-PV** [comment]
Notes: 

_If you show the code in the story, the Badge shows up as [object Object] due to the forwardRef trouble. Until we remove WP element, I think we should use the StorybookComponent so it displays nicely in the code._

1) The previous point will be approached in the following [PR](https://github.com/Yoast/wordpress-seo/pull/20944) where `StorybookComponent` is refactored. 

_Add the isVisible property to the proptypes._

2) After discussing it, we decided to not include the `isVisible` prop in the **Tooltip**.
